-- AlterTable
ALTER TABLE "GameTable" ADD COLUMN     "ante" DECIMAL(20,2) NOT NULL DEFAULT 0,
ADD COLUMN     "isStraddleAllowed" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "password" TEXT,
ADD COLUMN     "timeBank" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "turnTime" INTEGER NOT NULL DEFAULT 30;
